// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trader.proto

package clmrpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountState int32

const (
	// The state of an account when it is pending its confirmation on-chain.
	AccountState_PENDING_OPEN AccountState = 0
	//
	//The state of an account when it has undergone an update on-chain either as
	//part of a matched order or a trader modification and it is pending its
	//confirmation on-chain.
	AccountState_PENDING_UPDATE AccountState = 1
	// The state of an account once it has confirmed on-chain.
	AccountState_OPEN AccountState = 2
	//
	//The state of an account once its expiration has been reached and its closing
	//transaction has confirmed.
	AccountState_EXPIRED AccountState = 3
	//
	//The state of an account when we're waiting for the closing transaction of
	//an account to confirm that required cooperation with the auctioneer.
	AccountState_PENDING_CLOSED AccountState = 4
	// The state of an account once its closing transaction has confirmed.
	AccountState_CLOSED AccountState = 5
	//
	//The state of an account that indicates that the account was attempted to be
	//recovered but failed because the opening transaction wasn't found by lnd.
	//This could be because it was never published or it never confirmed. Then the
	//funds are SAFU and the account can be considered to never have been opened
	//in the first place.
	AccountState_RECOVERY_FAILED AccountState = 6
)

var AccountState_name = map[int32]string{
	0: "PENDING_OPEN",
	1: "PENDING_UPDATE",
	2: "OPEN",
	3: "EXPIRED",
	4: "PENDING_CLOSED",
	5: "CLOSED",
	6: "RECOVERY_FAILED",
}

var AccountState_value = map[string]int32{
	"PENDING_OPEN":    0,
	"PENDING_UPDATE":  1,
	"OPEN":            2,
	"EXPIRED":         3,
	"PENDING_CLOSED":  4,
	"CLOSED":          5,
	"RECOVERY_FAILED": 6,
}

func (x AccountState) String() string {
	return proto.EnumName(AccountState_name, int32(x))
}

func (AccountState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{0}
}

type InitAccountRequest struct {
	AccountValue uint64 `protobuf:"varint,1,opt,name=account_value,json=accountValue,proto3" json:"account_value,omitempty"`
	// Types that are valid to be assigned to AccountExpiry:
	//	*InitAccountRequest_AbsoluteHeight
	//	*InitAccountRequest_RelativeHeight
	AccountExpiry        isInitAccountRequest_AccountExpiry `protobuf_oneof:"account_expiry"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *InitAccountRequest) Reset()         { *m = InitAccountRequest{} }
func (m *InitAccountRequest) String() string { return proto.CompactTextString(m) }
func (*InitAccountRequest) ProtoMessage()    {}
func (*InitAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{0}
}

func (m *InitAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitAccountRequest.Unmarshal(m, b)
}
func (m *InitAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitAccountRequest.Marshal(b, m, deterministic)
}
func (m *InitAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitAccountRequest.Merge(m, src)
}
func (m *InitAccountRequest) XXX_Size() int {
	return xxx_messageInfo_InitAccountRequest.Size(m)
}
func (m *InitAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitAccountRequest proto.InternalMessageInfo

func (m *InitAccountRequest) GetAccountValue() uint64 {
	if m != nil {
		return m.AccountValue
	}
	return 0
}

type isInitAccountRequest_AccountExpiry interface {
	isInitAccountRequest_AccountExpiry()
}

type InitAccountRequest_AbsoluteHeight struct {
	AbsoluteHeight uint32 `protobuf:"varint,2,opt,name=absolute_height,json=absoluteHeight,proto3,oneof"`
}

type InitAccountRequest_RelativeHeight struct {
	RelativeHeight uint32 `protobuf:"varint,3,opt,name=relative_height,json=relativeHeight,proto3,oneof"`
}

func (*InitAccountRequest_AbsoluteHeight) isInitAccountRequest_AccountExpiry() {}

func (*InitAccountRequest_RelativeHeight) isInitAccountRequest_AccountExpiry() {}

func (m *InitAccountRequest) GetAccountExpiry() isInitAccountRequest_AccountExpiry {
	if m != nil {
		return m.AccountExpiry
	}
	return nil
}

func (m *InitAccountRequest) GetAbsoluteHeight() uint32 {
	if x, ok := m.GetAccountExpiry().(*InitAccountRequest_AbsoluteHeight); ok {
		return x.AbsoluteHeight
	}
	return 0
}

func (m *InitAccountRequest) GetRelativeHeight() uint32 {
	if x, ok := m.GetAccountExpiry().(*InitAccountRequest_RelativeHeight); ok {
		return x.RelativeHeight
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*InitAccountRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*InitAccountRequest_AbsoluteHeight)(nil),
		(*InitAccountRequest_RelativeHeight)(nil),
	}
}

type ListAccountsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{1}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

type ListAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{2}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type Output struct {
	// The value, in satoshis, of the output.
	ValueSat uint64 `protobuf:"varint,1,opt,name=value_sat,json=valueSat,proto3" json:"value_sat,omitempty"`
	// The address corresponding to the output.
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{3}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetValueSat() uint64 {
	if m != nil {
		return m.ValueSat
	}
	return 0
}

func (m *Output) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CloseAccountRequest struct {
	// The trader key associated with the account that will be closed.
	TraderKey []byte `protobuf:"bytes,1,opt,name=trader_key,json=traderKey,proto3" json:"trader_key,omitempty"`
	//
	//The outputs that should be created as a result of closing the account. If
	//none are specified, then the funds within the account are sent to an address
	//the backing lnd node controls.
	Outputs              []*Output `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CloseAccountRequest) Reset()         { *m = CloseAccountRequest{} }
func (m *CloseAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CloseAccountRequest) ProtoMessage()    {}
func (*CloseAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{4}
}

func (m *CloseAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseAccountRequest.Unmarshal(m, b)
}
func (m *CloseAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseAccountRequest.Marshal(b, m, deterministic)
}
func (m *CloseAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseAccountRequest.Merge(m, src)
}
func (m *CloseAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CloseAccountRequest.Size(m)
}
func (m *CloseAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseAccountRequest proto.InternalMessageInfo

func (m *CloseAccountRequest) GetTraderKey() []byte {
	if m != nil {
		return m.TraderKey
	}
	return nil
}

func (m *CloseAccountRequest) GetOutputs() []*Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

type CloseAccountResponse struct {
	// The hash of the closing transaction.
	CloseTxid            []byte   `protobuf:"bytes,1,opt,name=close_txid,json=closeTxid,proto3" json:"close_txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseAccountResponse) Reset()         { *m = CloseAccountResponse{} }
func (m *CloseAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CloseAccountResponse) ProtoMessage()    {}
func (*CloseAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{5}
}

func (m *CloseAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseAccountResponse.Unmarshal(m, b)
}
func (m *CloseAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseAccountResponse.Marshal(b, m, deterministic)
}
func (m *CloseAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseAccountResponse.Merge(m, src)
}
func (m *CloseAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CloseAccountResponse.Size(m)
}
func (m *CloseAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseAccountResponse proto.InternalMessageInfo

func (m *CloseAccountResponse) GetCloseTxid() []byte {
	if m != nil {
		return m.CloseTxid
	}
	return nil
}

type WithdrawAccountRequest struct {
	//
	//The trader key associated with the account that funds will be withdrawed
	//from.
	TraderKey []byte `protobuf:"bytes,1,opt,name=trader_key,json=traderKey,proto3" json:"trader_key,omitempty"`
	// The outputs we'll withdraw funds from the account into.
	Outputs []*Output `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs,omitempty"`
	//
	//The fee rate, in satoshis per vbyte, to use for the withdrawal transaction.
	SatPerVbyte          uint64   `protobuf:"varint,3,opt,name=sat_per_vbyte,json=satPerVbyte,proto3" json:"sat_per_vbyte,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawAccountRequest) Reset()         { *m = WithdrawAccountRequest{} }
func (m *WithdrawAccountRequest) String() string { return proto.CompactTextString(m) }
func (*WithdrawAccountRequest) ProtoMessage()    {}
func (*WithdrawAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{6}
}

func (m *WithdrawAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawAccountRequest.Unmarshal(m, b)
}
func (m *WithdrawAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawAccountRequest.Marshal(b, m, deterministic)
}
func (m *WithdrawAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawAccountRequest.Merge(m, src)
}
func (m *WithdrawAccountRequest) XXX_Size() int {
	return xxx_messageInfo_WithdrawAccountRequest.Size(m)
}
func (m *WithdrawAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawAccountRequest proto.InternalMessageInfo

func (m *WithdrawAccountRequest) GetTraderKey() []byte {
	if m != nil {
		return m.TraderKey
	}
	return nil
}

func (m *WithdrawAccountRequest) GetOutputs() []*Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *WithdrawAccountRequest) GetSatPerVbyte() uint64 {
	if m != nil {
		return m.SatPerVbyte
	}
	return 0
}

type WithdrawAccountResponse struct {
	// The state of the account after processing the withdrawal.
	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// The transaction used to withdraw funds from the account.
	WithdrawTxid         []byte   `protobuf:"bytes,2,opt,name=withdraw_txid,json=withdrawTxid,proto3" json:"withdraw_txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithdrawAccountResponse) Reset()         { *m = WithdrawAccountResponse{} }
func (m *WithdrawAccountResponse) String() string { return proto.CompactTextString(m) }
func (*WithdrawAccountResponse) ProtoMessage()    {}
func (*WithdrawAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{7}
}

func (m *WithdrawAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawAccountResponse.Unmarshal(m, b)
}
func (m *WithdrawAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawAccountResponse.Marshal(b, m, deterministic)
}
func (m *WithdrawAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawAccountResponse.Merge(m, src)
}
func (m *WithdrawAccountResponse) XXX_Size() int {
	return xxx_messageInfo_WithdrawAccountResponse.Size(m)
}
func (m *WithdrawAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawAccountResponse proto.InternalMessageInfo

func (m *WithdrawAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *WithdrawAccountResponse) GetWithdrawTxid() []byte {
	if m != nil {
		return m.WithdrawTxid
	}
	return nil
}

type DepositAccountRequest struct {
	//
	//The trader key associated with the account that funds will be deposited
	//into.
	TraderKey []byte `protobuf:"bytes,1,opt,name=trader_key,json=traderKey,proto3" json:"trader_key,omitempty"`
	// The amount in satoshis to deposit into the account.
	AmountSat uint64 `protobuf:"varint,2,opt,name=amount_sat,json=amountSat,proto3" json:"amount_sat,omitempty"`
	//
	//The fee rate, in satoshis per vbyte, to use for the deposit transaction.
	SatPerVbyte          uint32   `protobuf:"varint,3,opt,name=sat_per_vbyte,json=satPerVbyte,proto3" json:"sat_per_vbyte,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositAccountRequest) Reset()         { *m = DepositAccountRequest{} }
func (m *DepositAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DepositAccountRequest) ProtoMessage()    {}
func (*DepositAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{8}
}

func (m *DepositAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositAccountRequest.Unmarshal(m, b)
}
func (m *DepositAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositAccountRequest.Marshal(b, m, deterministic)
}
func (m *DepositAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositAccountRequest.Merge(m, src)
}
func (m *DepositAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DepositAccountRequest.Size(m)
}
func (m *DepositAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositAccountRequest proto.InternalMessageInfo

func (m *DepositAccountRequest) GetTraderKey() []byte {
	if m != nil {
		return m.TraderKey
	}
	return nil
}

func (m *DepositAccountRequest) GetAmountSat() uint64 {
	if m != nil {
		return m.AmountSat
	}
	return 0
}

func (m *DepositAccountRequest) GetSatPerVbyte() uint32 {
	if m != nil {
		return m.SatPerVbyte
	}
	return 0
}

type DepositAccountResponse struct {
	// The state of the account after processing the deposit.
	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// The transaction used to deposit funds into the account.
	DepositTxid          []byte   `protobuf:"bytes,2,opt,name=deposit_txid,json=depositTxid,proto3" json:"deposit_txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositAccountResponse) Reset()         { *m = DepositAccountResponse{} }
func (m *DepositAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DepositAccountResponse) ProtoMessage()    {}
func (*DepositAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{9}
}

func (m *DepositAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositAccountResponse.Unmarshal(m, b)
}
func (m *DepositAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositAccountResponse.Marshal(b, m, deterministic)
}
func (m *DepositAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositAccountResponse.Merge(m, src)
}
func (m *DepositAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DepositAccountResponse.Size(m)
}
func (m *DepositAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepositAccountResponse proto.InternalMessageInfo

func (m *DepositAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *DepositAccountResponse) GetDepositTxid() []byte {
	if m != nil {
		return m.DepositTxid
	}
	return nil
}

type Account struct {
	//
	//The identifying component of an account. This is the key used for the trader
	//in the 2-of-2 multi-sig construction of an account with an auctioneer.
	TraderKey []byte `protobuf:"bytes,1,opt,name=trader_key,json=traderKey,proto3" json:"trader_key,omitempty"`
	//
	//The current outpoint associated with the account. This will change every
	//time the account has been updated.
	Outpoint *OutPoint `protobuf:"bytes,2,opt,name=outpoint,proto3" json:"outpoint,omitempty"`
	// The current value in satoshis of the account.
	Value uint64 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	// The height at which the account will expire.
	ExpirationHeight uint32 `protobuf:"varint,4,opt,name=expiration_height,json=expirationHeight,proto3" json:"expiration_height,omitempty"`
	// The current state of the account.
	State AccountState `protobuf:"varint,5,opt,name=state,proto3,enum=clmrpc.AccountState" json:"state,omitempty"`
	// The hash of the account's closing transaction, if any.
	CloseTxid            []byte   `protobuf:"bytes,6,opt,name=close_txid,json=closeTxid,proto3" json:"close_txid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{10}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetTraderKey() []byte {
	if m != nil {
		return m.TraderKey
	}
	return nil
}

func (m *Account) GetOutpoint() *OutPoint {
	if m != nil {
		return m.Outpoint
	}
	return nil
}

func (m *Account) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Account) GetExpirationHeight() uint32 {
	if m != nil {
		return m.ExpirationHeight
	}
	return 0
}

func (m *Account) GetState() AccountState {
	if m != nil {
		return m.State
	}
	return AccountState_PENDING_OPEN
}

func (m *Account) GetCloseTxid() []byte {
	if m != nil {
		return m.CloseTxid
	}
	return nil
}

type SubmitOrderRequest struct {
	// Types that are valid to be assigned to Details:
	//	*SubmitOrderRequest_Ask
	//	*SubmitOrderRequest_Bid
	Details              isSubmitOrderRequest_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SubmitOrderRequest) Reset()         { *m = SubmitOrderRequest{} }
func (m *SubmitOrderRequest) String() string { return proto.CompactTextString(m) }
func (*SubmitOrderRequest) ProtoMessage()    {}
func (*SubmitOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{11}
}

func (m *SubmitOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitOrderRequest.Unmarshal(m, b)
}
func (m *SubmitOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitOrderRequest.Marshal(b, m, deterministic)
}
func (m *SubmitOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitOrderRequest.Merge(m, src)
}
func (m *SubmitOrderRequest) XXX_Size() int {
	return xxx_messageInfo_SubmitOrderRequest.Size(m)
}
func (m *SubmitOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitOrderRequest proto.InternalMessageInfo

type isSubmitOrderRequest_Details interface {
	isSubmitOrderRequest_Details()
}

type SubmitOrderRequest_Ask struct {
	Ask *Ask `protobuf:"bytes,1,opt,name=ask,proto3,oneof"`
}

type SubmitOrderRequest_Bid struct {
	Bid *Bid `protobuf:"bytes,2,opt,name=bid,proto3,oneof"`
}

func (*SubmitOrderRequest_Ask) isSubmitOrderRequest_Details() {}

func (*SubmitOrderRequest_Bid) isSubmitOrderRequest_Details() {}

func (m *SubmitOrderRequest) GetDetails() isSubmitOrderRequest_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *SubmitOrderRequest) GetAsk() *Ask {
	if x, ok := m.GetDetails().(*SubmitOrderRequest_Ask); ok {
		return x.Ask
	}
	return nil
}

func (m *SubmitOrderRequest) GetBid() *Bid {
	if x, ok := m.GetDetails().(*SubmitOrderRequest_Bid); ok {
		return x.Bid
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SubmitOrderRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SubmitOrderRequest_Ask)(nil),
		(*SubmitOrderRequest_Bid)(nil),
	}
}

type SubmitOrderResponse struct {
	// Types that are valid to be assigned to Details:
	//	*SubmitOrderResponse_InvalidOrder
	//	*SubmitOrderResponse_AcceptedOrderNonce
	Details              isSubmitOrderResponse_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SubmitOrderResponse) Reset()         { *m = SubmitOrderResponse{} }
func (m *SubmitOrderResponse) String() string { return proto.CompactTextString(m) }
func (*SubmitOrderResponse) ProtoMessage()    {}
func (*SubmitOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{12}
}

func (m *SubmitOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitOrderResponse.Unmarshal(m, b)
}
func (m *SubmitOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitOrderResponse.Marshal(b, m, deterministic)
}
func (m *SubmitOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitOrderResponse.Merge(m, src)
}
func (m *SubmitOrderResponse) XXX_Size() int {
	return xxx_messageInfo_SubmitOrderResponse.Size(m)
}
func (m *SubmitOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitOrderResponse proto.InternalMessageInfo

type isSubmitOrderResponse_Details interface {
	isSubmitOrderResponse_Details()
}

type SubmitOrderResponse_InvalidOrder struct {
	InvalidOrder *InvalidOrder `protobuf:"bytes,1,opt,name=invalid_order,json=invalidOrder,proto3,oneof"`
}

type SubmitOrderResponse_AcceptedOrderNonce struct {
	AcceptedOrderNonce []byte `protobuf:"bytes,2,opt,name=accepted_order_nonce,json=acceptedOrderNonce,proto3,oneof"`
}

func (*SubmitOrderResponse_InvalidOrder) isSubmitOrderResponse_Details() {}

func (*SubmitOrderResponse_AcceptedOrderNonce) isSubmitOrderResponse_Details() {}

func (m *SubmitOrderResponse) GetDetails() isSubmitOrderResponse_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *SubmitOrderResponse) GetInvalidOrder() *InvalidOrder {
	if x, ok := m.GetDetails().(*SubmitOrderResponse_InvalidOrder); ok {
		return x.InvalidOrder
	}
	return nil
}

func (m *SubmitOrderResponse) GetAcceptedOrderNonce() []byte {
	if x, ok := m.GetDetails().(*SubmitOrderResponse_AcceptedOrderNonce); ok {
		return x.AcceptedOrderNonce
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SubmitOrderResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SubmitOrderResponse_InvalidOrder)(nil),
		(*SubmitOrderResponse_AcceptedOrderNonce)(nil),
	}
}

type ListOrdersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrdersRequest) Reset()         { *m = ListOrdersRequest{} }
func (m *ListOrdersRequest) String() string { return proto.CompactTextString(m) }
func (*ListOrdersRequest) ProtoMessage()    {}
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{13}
}

func (m *ListOrdersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrdersRequest.Unmarshal(m, b)
}
func (m *ListOrdersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrdersRequest.Marshal(b, m, deterministic)
}
func (m *ListOrdersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrdersRequest.Merge(m, src)
}
func (m *ListOrdersRequest) XXX_Size() int {
	return xxx_messageInfo_ListOrdersRequest.Size(m)
}
func (m *ListOrdersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrdersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrdersRequest proto.InternalMessageInfo

type ListOrdersResponse struct {
	Asks                 []*Ask   `protobuf:"bytes,1,rep,name=asks,proto3" json:"asks,omitempty"`
	Bids                 []*Bid   `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrdersResponse) Reset()         { *m = ListOrdersResponse{} }
func (m *ListOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*ListOrdersResponse) ProtoMessage()    {}
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{14}
}

func (m *ListOrdersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrdersResponse.Unmarshal(m, b)
}
func (m *ListOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrdersResponse.Marshal(b, m, deterministic)
}
func (m *ListOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrdersResponse.Merge(m, src)
}
func (m *ListOrdersResponse) XXX_Size() int {
	return xxx_messageInfo_ListOrdersResponse.Size(m)
}
func (m *ListOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrdersResponse proto.InternalMessageInfo

func (m *ListOrdersResponse) GetAsks() []*Ask {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *ListOrdersResponse) GetBids() []*Bid {
	if m != nil {
		return m.Bids
	}
	return nil
}

type CancelOrderRequest struct {
	OrderNonce           []byte   `protobuf:"bytes,1,opt,name=order_nonce,json=orderNonce,proto3" json:"order_nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderRequest) Reset()         { *m = CancelOrderRequest{} }
func (m *CancelOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CancelOrderRequest) ProtoMessage()    {}
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{15}
}

func (m *CancelOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderRequest.Unmarshal(m, b)
}
func (m *CancelOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderRequest.Marshal(b, m, deterministic)
}
func (m *CancelOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderRequest.Merge(m, src)
}
func (m *CancelOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CancelOrderRequest.Size(m)
}
func (m *CancelOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderRequest proto.InternalMessageInfo

func (m *CancelOrderRequest) GetOrderNonce() []byte {
	if m != nil {
		return m.OrderNonce
	}
	return nil
}

type CancelOrderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CancelOrderResponse) Reset()         { *m = CancelOrderResponse{} }
func (m *CancelOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CancelOrderResponse) ProtoMessage()    {}
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{16}
}

func (m *CancelOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CancelOrderResponse.Unmarshal(m, b)
}
func (m *CancelOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CancelOrderResponse.Marshal(b, m, deterministic)
}
func (m *CancelOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CancelOrderResponse.Merge(m, src)
}
func (m *CancelOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CancelOrderResponse.Size(m)
}
func (m *CancelOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CancelOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CancelOrderResponse proto.InternalMessageInfo

type Order struct {
	//
	//The trader's account key of the account that is used for the order.
	TraderKey []byte `protobuf:"bytes,1,opt,name=trader_key,json=traderKey,proto3" json:"trader_key,omitempty"`
	//
	//Fixed order rate in parts per billion.
	RateFixed uint32 `protobuf:"varint,2,opt,name=rate_fixed,json=rateFixed,proto3" json:"rate_fixed,omitempty"`
	//
	//Order amount in satoshis.
	Amt uint64 `protobuf:"varint,3,opt,name=amt,proto3" json:"amt,omitempty"`
	//
	//Preferred fee rate to be used for the channel funding transaction, expressed
	//in satoshis per 1000 weight units (sat/kW).
	FundingFeeRate uint64 `protobuf:"varint,4,opt,name=funding_fee_rate,json=fundingFeeRate,proto3" json:"funding_fee_rate,omitempty"`
	//
	//Order nonce, acts as unique order identifier.
	OrderNonce []byte `protobuf:"bytes,5,opt,name=order_nonce,json=orderNonce,proto3" json:"order_nonce,omitempty"`
	//
	//The state the order currently is in.
	State OrderState `protobuf:"varint,6,opt,name=state,proto3,enum=clmrpc.OrderState" json:"state,omitempty"`
	//
	//The number of order units the amount corresponds to.
	Units uint32 `protobuf:"varint,7,opt,name=units,proto3" json:"units,omitempty"`
	//
	//The number of currently unfilled units of this order. This will be equal to
	//the total amount of units until the order has reached the state PARTIAL_FILL
	//or EXECUTED.
	UnitsUnfulfilled     uint32   `protobuf:"varint,8,opt,name=units_unfulfilled,json=unitsUnfulfilled,proto3" json:"units_unfulfilled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{17}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetTraderKey() []byte {
	if m != nil {
		return m.TraderKey
	}
	return nil
}

func (m *Order) GetRateFixed() uint32 {
	if m != nil {
		return m.RateFixed
	}
	return 0
}

func (m *Order) GetAmt() uint64 {
	if m != nil {
		return m.Amt
	}
	return 0
}

func (m *Order) GetFundingFeeRate() uint64 {
	if m != nil {
		return m.FundingFeeRate
	}
	return 0
}

func (m *Order) GetOrderNonce() []byte {
	if m != nil {
		return m.OrderNonce
	}
	return nil
}

func (m *Order) GetState() OrderState {
	if m != nil {
		return m.State
	}
	return OrderState_ORDER_SUBMITTED
}

func (m *Order) GetUnits() uint32 {
	if m != nil {
		return m.Units
	}
	return 0
}

func (m *Order) GetUnitsUnfulfilled() uint32 {
	if m != nil {
		return m.UnitsUnfulfilled
	}
	return 0
}

type Bid struct {
	//
	//The common fields shared between both ask and bid order types.
	Details *Order `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	//
	//Required minimum number of blocks that a channel opened as a result of this
	//bid should be kept open.
	MinDurationBlocks uint32 `protobuf:"varint,2,opt,name=min_duration_blocks,json=minDurationBlocks,proto3" json:"min_duration_blocks,omitempty"`
	//
	//The version of the order format that is used. Will be increased once new
	//features are added.
	Version              uint32   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bid) Reset()         { *m = Bid{} }
func (m *Bid) String() string { return proto.CompactTextString(m) }
func (*Bid) ProtoMessage()    {}
func (*Bid) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{18}
}

func (m *Bid) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bid.Unmarshal(m, b)
}
func (m *Bid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bid.Marshal(b, m, deterministic)
}
func (m *Bid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bid.Merge(m, src)
}
func (m *Bid) XXX_Size() int {
	return xxx_messageInfo_Bid.Size(m)
}
func (m *Bid) XXX_DiscardUnknown() {
	xxx_messageInfo_Bid.DiscardUnknown(m)
}

var xxx_messageInfo_Bid proto.InternalMessageInfo

func (m *Bid) GetDetails() *Order {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Bid) GetMinDurationBlocks() uint32 {
	if m != nil {
		return m.MinDurationBlocks
	}
	return 0
}

func (m *Bid) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type Ask struct {
	//
	//The common fields shared between both ask and bid order types.
	Details *Order `protobuf:"bytes,1,opt,name=details,proto3" json:"details,omitempty"`
	//
	//The maximum number of blocks the liquidity provider is willing to provide
	//the channel funds for.
	MaxDurationBlocks uint32 `protobuf:"varint,2,opt,name=max_duration_blocks,json=maxDurationBlocks,proto3" json:"max_duration_blocks,omitempty"`
	//
	//The version of the order format that is used. Will be increased once new
	//features are added.
	Version              uint32   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ask) Reset()         { *m = Ask{} }
func (m *Ask) String() string { return proto.CompactTextString(m) }
func (*Ask) ProtoMessage()    {}
func (*Ask) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{19}
}

func (m *Ask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ask.Unmarshal(m, b)
}
func (m *Ask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ask.Marshal(b, m, deterministic)
}
func (m *Ask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ask.Merge(m, src)
}
func (m *Ask) XXX_Size() int {
	return xxx_messageInfo_Ask.Size(m)
}
func (m *Ask) XXX_DiscardUnknown() {
	xxx_messageInfo_Ask.DiscardUnknown(m)
}

var xxx_messageInfo_Ask proto.InternalMessageInfo

func (m *Ask) GetDetails() *Order {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Ask) GetMaxDurationBlocks() uint32 {
	if m != nil {
		return m.MaxDurationBlocks
	}
	return 0
}

func (m *Ask) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type RecoverAccountsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverAccountsRequest) Reset()         { *m = RecoverAccountsRequest{} }
func (m *RecoverAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*RecoverAccountsRequest) ProtoMessage()    {}
func (*RecoverAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{20}
}

func (m *RecoverAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverAccountsRequest.Unmarshal(m, b)
}
func (m *RecoverAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverAccountsRequest.Marshal(b, m, deterministic)
}
func (m *RecoverAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverAccountsRequest.Merge(m, src)
}
func (m *RecoverAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_RecoverAccountsRequest.Size(m)
}
func (m *RecoverAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverAccountsRequest proto.InternalMessageInfo

type RecoverAccountsResponse struct {
	// The number of accounts that were recovered.
	NumRecoveredAccounts uint32   `protobuf:"varint,1,opt,name=num_recovered_accounts,json=numRecoveredAccounts,proto3" json:"num_recovered_accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecoverAccountsResponse) Reset()         { *m = RecoverAccountsResponse{} }
func (m *RecoverAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*RecoverAccountsResponse) ProtoMessage()    {}
func (*RecoverAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{21}
}

func (m *RecoverAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecoverAccountsResponse.Unmarshal(m, b)
}
func (m *RecoverAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecoverAccountsResponse.Marshal(b, m, deterministic)
}
func (m *RecoverAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecoverAccountsResponse.Merge(m, src)
}
func (m *RecoverAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_RecoverAccountsResponse.Size(m)
}
func (m *RecoverAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RecoverAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RecoverAccountsResponse proto.InternalMessageInfo

func (m *RecoverAccountsResponse) GetNumRecoveredAccounts() uint32 {
	if m != nil {
		return m.NumRecoveredAccounts
	}
	return 0
}

type AuctionFeeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuctionFeeRequest) Reset()         { *m = AuctionFeeRequest{} }
func (m *AuctionFeeRequest) String() string { return proto.CompactTextString(m) }
func (*AuctionFeeRequest) ProtoMessage()    {}
func (*AuctionFeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{22}
}

func (m *AuctionFeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuctionFeeRequest.Unmarshal(m, b)
}
func (m *AuctionFeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuctionFeeRequest.Marshal(b, m, deterministic)
}
func (m *AuctionFeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuctionFeeRequest.Merge(m, src)
}
func (m *AuctionFeeRequest) XXX_Size() int {
	return xxx_messageInfo_AuctionFeeRequest.Size(m)
}
func (m *AuctionFeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuctionFeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuctionFeeRequest proto.InternalMessageInfo

type AuctionFeeResponse struct {
	//
	//The execution fee charged per matched order.
	ExecutionFee         *ExecutionFee `protobuf:"bytes,1,opt,name=execution_fee,json=executionFee,proto3" json:"execution_fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AuctionFeeResponse) Reset()         { *m = AuctionFeeResponse{} }
func (m *AuctionFeeResponse) String() string { return proto.CompactTextString(m) }
func (*AuctionFeeResponse) ProtoMessage()    {}
func (*AuctionFeeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8f61804588c75fe, []int{23}
}

func (m *AuctionFeeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuctionFeeResponse.Unmarshal(m, b)
}
func (m *AuctionFeeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuctionFeeResponse.Marshal(b, m, deterministic)
}
func (m *AuctionFeeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuctionFeeResponse.Merge(m, src)
}
func (m *AuctionFeeResponse) XXX_Size() int {
	return xxx_messageInfo_AuctionFeeResponse.Size(m)
}
func (m *AuctionFeeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuctionFeeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuctionFeeResponse proto.InternalMessageInfo

func (m *AuctionFeeResponse) GetExecutionFee() *ExecutionFee {
	if m != nil {
		return m.ExecutionFee
	}
	return nil
}

func init() {
	proto.RegisterEnum("clmrpc.AccountState", AccountState_name, AccountState_value)
	proto.RegisterType((*InitAccountRequest)(nil), "clmrpc.InitAccountRequest")
	proto.RegisterType((*ListAccountsRequest)(nil), "clmrpc.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "clmrpc.ListAccountsResponse")
	proto.RegisterType((*Output)(nil), "clmrpc.Output")
	proto.RegisterType((*CloseAccountRequest)(nil), "clmrpc.CloseAccountRequest")
	proto.RegisterType((*CloseAccountResponse)(nil), "clmrpc.CloseAccountResponse")
	proto.RegisterType((*WithdrawAccountRequest)(nil), "clmrpc.WithdrawAccountRequest")
	proto.RegisterType((*WithdrawAccountResponse)(nil), "clmrpc.WithdrawAccountResponse")
	proto.RegisterType((*DepositAccountRequest)(nil), "clmrpc.DepositAccountRequest")
	proto.RegisterType((*DepositAccountResponse)(nil), "clmrpc.DepositAccountResponse")
	proto.RegisterType((*Account)(nil), "clmrpc.Account")
	proto.RegisterType((*SubmitOrderRequest)(nil), "clmrpc.SubmitOrderRequest")
	proto.RegisterType((*SubmitOrderResponse)(nil), "clmrpc.SubmitOrderResponse")
	proto.RegisterType((*ListOrdersRequest)(nil), "clmrpc.ListOrdersRequest")
	proto.RegisterType((*ListOrdersResponse)(nil), "clmrpc.ListOrdersResponse")
	proto.RegisterType((*CancelOrderRequest)(nil), "clmrpc.CancelOrderRequest")
	proto.RegisterType((*CancelOrderResponse)(nil), "clmrpc.CancelOrderResponse")
	proto.RegisterType((*Order)(nil), "clmrpc.Order")
	proto.RegisterType((*Bid)(nil), "clmrpc.Bid")
	proto.RegisterType((*Ask)(nil), "clmrpc.Ask")
	proto.RegisterType((*RecoverAccountsRequest)(nil), "clmrpc.RecoverAccountsRequest")
	proto.RegisterType((*RecoverAccountsResponse)(nil), "clmrpc.RecoverAccountsResponse")
	proto.RegisterType((*AuctionFeeRequest)(nil), "clmrpc.AuctionFeeRequest")
	proto.RegisterType((*AuctionFeeResponse)(nil), "clmrpc.AuctionFeeResponse")
}

func init() { proto.RegisterFile("trader.proto", fileDescriptor_b8f61804588c75fe) }

var fileDescriptor_b8f61804588c75fe = []byte{
	// 1424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0x8f, 0x13, 0xff, 0x89, 0xc7, 0x7f, 0x72, 0x5d, 0xbb, 0xa9, 0xeb, 0x34, 0x69, 0xb8, 0x82,
	0x70, 0x53, 0x14, 0x8b, 0x40, 0x1f, 0x80, 0x07, 0x14, 0xc7, 0x2e, 0x89, 0xa8, 0x92, 0xe8, 0xd2,
	0xa6, 0x05, 0x24, 0x4e, 0xeb, 0xbb, 0x75, 0xb2, 0xca, 0xf9, 0xce, 0xdc, 0xed, 0xb9, 0x8e, 0x10,
	0x12, 0x42, 0xe2, 0x85, 0x17, 0x84, 0xf8, 0x04, 0x7c, 0x26, 0xbe, 0x42, 0x3f, 0x08, 0xda, 0xbd,
	0x5d, 0xdf, 0xf9, 0xec, 0x10, 0xfa, 0xc0, 0x9b, 0x6f, 0x7e, 0xb3, 0xf3, 0x9b, 0xd9, 0x99, 0xd9,
	0x19, 0x43, 0x99, 0xf9, 0xd8, 0x26, 0xfe, 0xee, 0xc8, 0xf7, 0x98, 0x87, 0xf2, 0x96, 0x33, 0xf4,
	0x47, 0x56, 0xf3, 0xc1, 0x85, 0xe7, 0x5d, 0x38, 0xa4, 0x8d, 0x47, 0xb4, 0x8d, 0x5d, 0xd7, 0x63,
	0x98, 0x51, 0xcf, 0x0d, 0x22, 0xad, 0xa6, 0x86, 0x43, 0x8b, 0x7f, 0x13, 0x75, 0x4e, 0xff, 0x2b,
	0x03, 0xe8, 0xc8, 0xa5, 0x6c, 0xdf, 0xb2, 0xbc, 0xd0, 0x65, 0x06, 0xf9, 0x21, 0x24, 0x01, 0x43,
	0x8f, 0xa0, 0x82, 0x23, 0x89, 0x39, 0xc6, 0x4e, 0x48, 0x1a, 0x99, 0xed, 0x4c, 0x2b, 0x6b, 0x94,
	0xa5, 0xf0, 0x9c, 0xcb, 0xd0, 0x63, 0x58, 0xc3, 0xfd, 0xc0, 0x73, 0x42, 0x46, 0xcc, 0x4b, 0x42,
	0x2f, 0x2e, 0x59, 0x63, 0x79, 0x3b, 0xd3, 0xaa, 0x1c, 0x2e, 0x19, 0x55, 0x05, 0x1c, 0x0a, 0x39,
	0x57, 0xf5, 0x89, 0x83, 0x19, 0x1d, 0x4f, 0x55, 0x57, 0x94, 0xaa, 0x02, 0x22, 0xd5, 0x8e, 0x06,
	0x55, 0x45, 0x4d, 0x26, 0x23, 0xea, 0x5f, 0xeb, 0x77, 0xa1, 0xf6, 0x9c, 0x06, 0xca, 0xc5, 0x40,
	0xfa, 0xa8, 0x1f, 0x40, 0x7d, 0x56, 0x1c, 0x8c, 0x3c, 0x37, 0x20, 0xe8, 0x09, 0xac, 0x4a, 0x03,
	0x41, 0x23, 0xb3, 0xbd, 0xd2, 0x2a, 0xed, 0xad, 0xed, 0x46, 0xb7, 0xb3, 0xab, 0xa2, 0x9c, 0x2a,
	0xe8, 0x5f, 0x42, 0xfe, 0x24, 0x64, 0xa3, 0x90, 0xa1, 0x0d, 0x28, 0x8a, 0x50, 0xcd, 0x00, 0x33,
	0x19, 0xee, 0xaa, 0x10, 0x9c, 0x61, 0x86, 0x1a, 0x50, 0xc0, 0xb6, 0xed, 0x93, 0x20, 0x10, 0x21,
	0x16, 0x0d, 0xf5, 0xa9, 0x7f, 0x0f, 0xb5, 0x03, 0xc7, 0x0b, 0x48, 0xea, 0x02, 0x37, 0x01, 0xa2,
	0xfc, 0x98, 0x57, 0xe4, 0x5a, 0x98, 0x2b, 0x1b, 0xc5, 0x48, 0xf2, 0x35, 0xb9, 0x46, 0x2d, 0x28,
	0x78, 0x82, 0x96, 0xdb, 0xe3, 0x2e, 0x56, 0x95, 0x8b, 0x91, 0x37, 0x86, 0x82, 0xf5, 0xa7, 0x50,
	0x9f, 0xb5, 0x2f, 0xa3, 0xdc, 0x04, 0xb0, 0xb8, 0xdc, 0x64, 0x13, 0x6a, 0x2b, 0x02, 0x21, 0x79,
	0x31, 0xa1, 0xb6, 0xfe, 0x6b, 0x06, 0xd6, 0x5f, 0x51, 0x76, 0x69, 0xfb, 0xf8, 0xcd, 0xff, 0xe4,
	0x1a, 0xd2, 0xa1, 0x12, 0x60, 0x66, 0x8e, 0x88, 0x6f, 0x8e, 0xfb, 0xd7, 0x8c, 0x88, 0x94, 0x66,
	0x8d, 0x52, 0x80, 0xd9, 0x29, 0xf1, 0xcf, 0xb9, 0x48, 0xa7, 0x70, 0x6f, 0xce, 0x0d, 0x19, 0xc1,
	0x63, 0x28, 0xc8, 0x34, 0x08, 0x27, 0x16, 0xa4, 0x49, 0xe1, 0xbc, 0x1c, 0xdf, 0x48, 0x2b, 0x51,
	0xbc, 0xcb, 0xc2, 0xeb, 0xb2, 0x12, 0x8a, 0x90, 0xaf, 0xe1, 0x6e, 0x97, 0x8c, 0xbc, 0x60, 0xae,
	0x98, 0x6f, 0x09, 0x78, 0x13, 0x00, 0x0f, 0x45, 0xbd, 0xf1, 0xcc, 0x2f, 0x8b, 0x18, 0x8a, 0x91,
	0x84, 0xa7, 0x7e, 0x61, 0x94, 0x95, 0xd9, 0x28, 0x07, 0xb0, 0x9e, 0xa6, 0x7e, 0xf7, 0x20, 0xdf,
	0x83, 0xb2, 0x1d, 0x19, 0x49, 0xc6, 0x58, 0x92, 0x32, 0x11, 0xe2, 0xdb, 0x0c, 0x14, 0xe4, 0xb9,
	0xdb, 0xa2, 0xfa, 0x08, 0x56, 0x79, 0x9e, 0x3c, 0xea, 0x46, 0x31, 0x95, 0xf6, 0xb4, 0x44, 0x1e,
	0x4f, 0xb9, 0xdc, 0x98, 0x6a, 0xa0, 0x3a, 0xe4, 0xa2, 0x3e, 0x8f, 0x52, 0x18, 0x7d, 0xa0, 0x27,
	0x70, 0x47, 0xb4, 0xa0, 0x78, 0x43, 0x54, 0xdf, 0x66, 0x45, 0xf8, 0x5a, 0x0c, 0xc8, 0x16, 0xdf,
	0x81, 0x5c, 0xc0, 0x30, 0x23, 0x8d, 0xdc, 0x76, 0xa6, 0x55, 0xdd, 0xab, 0xa7, 0xe2, 0x3c, 0xe3,
	0x98, 0x11, 0xa9, 0xa4, 0x8a, 0x37, 0x9f, 0x2e, 0x5e, 0x0c, 0xe8, 0x2c, 0xec, 0x0f, 0x29, 0x3b,
	0xf1, 0x6d, 0xe2, 0xab, 0x34, 0x3e, 0x84, 0x15, 0x1c, 0x5c, 0xc9, 0x6b, 0x2c, 0x4d, 0xcd, 0x07,
	0x57, 0x87, 0x4b, 0x06, 0x47, 0xb8, 0x42, 0x5f, 0xde, 0x5b, 0x42, 0xa1, 0x43, 0x6d, 0xae, 0xd0,
	0xa7, 0x76, 0xa7, 0x08, 0x05, 0x9b, 0x30, 0x4c, 0x9d, 0x40, 0xff, 0x23, 0x03, 0xb5, 0x19, 0x0e,
	0x99, 0xaf, 0x2f, 0xa0, 0x42, 0xdd, 0x31, 0x76, 0xa8, 0x6d, 0x7a, 0x1c, 0x90, 0x74, 0xd3, 0x68,
	0x8e, 0x22, 0x50, 0x1c, 0x3a, 0x5c, 0x32, 0xca, 0x34, 0xf1, 0x8d, 0xf6, 0xa0, 0x8e, 0x2d, 0x8b,
	0x8c, 0x18, 0x91, 0xa7, 0x4d, 0xd7, 0x73, 0x2d, 0x12, 0x65, 0xf2, 0x70, 0xc9, 0x40, 0x0a, 0x15,
	0xea, 0xc7, 0x1c, 0x4b, 0xfa, 0x54, 0x83, 0x3b, 0xfc, 0x41, 0x13, 0xe0, 0xf4, 0x95, 0x3b, 0x07,
	0x94, 0x14, 0x4a, 0x37, 0x1f, 0x42, 0x16, 0x07, 0x57, 0xea, 0x7d, 0x4b, 0x5e, 0x86, 0x21, 0x00,
	0xae, 0xd0, 0xa7, 0xb6, 0x6a, 0xe1, 0xe4, 0x65, 0x18, 0x02, 0xd0, 0x9f, 0x02, 0x3a, 0xc0, 0xae,
	0x45, 0x9c, 0xd4, 0x1d, 0x97, 0x92, 0x8e, 0x47, 0x55, 0x05, 0xde, 0xd4, 0x5d, 0xfe, 0x16, 0xcf,
	0x1c, 0x8b, 0xfc, 0xd1, 0x7f, 0x5f, 0x86, 0x5c, 0x74, 0x07, 0xb7, 0x37, 0x9b, 0x8f, 0x19, 0x31,
	0x07, 0x74, 0x42, 0xa2, 0x54, 0x55, 0x8c, 0x22, 0x97, 0x3c, 0xe3, 0x02, 0xa4, 0xc1, 0x0a, 0x1e,
	0x32, 0x59, 0x85, 0xfc, 0x27, 0x6a, 0x81, 0x36, 0x08, 0x5d, 0x9b, 0xba, 0x17, 0xe6, 0x80, 0x10,
	0x93, 0xab, 0x8a, 0x12, 0xcc, 0x1a, 0x55, 0x29, 0x7f, 0x46, 0x88, 0xc1, 0x8b, 0x2a, 0xe5, 0x7b,
	0x2e, 0xed, 0x3b, 0x6a, 0xa9, 0x0a, 0xcd, 0x8b, 0x0a, 0x45, 0xd3, 0x7e, 0xe0, 0x2a, 0x33, 0xf5,
	0x59, 0x87, 0x5c, 0xe8, 0x52, 0x16, 0x34, 0x0a, 0xc2, 0xc1, 0xe8, 0x83, 0xb7, 0x83, 0xf8, 0x61,
	0x86, 0xee, 0x20, 0x74, 0x06, 0xd4, 0x71, 0x88, 0xdd, 0x58, 0x8d, 0xda, 0x41, 0x00, 0x2f, 0x63,
	0xb9, 0x3e, 0x81, 0x95, 0x0e, 0xb5, 0xd1, 0x87, 0xd3, 0xf4, 0xca, 0x4a, 0xaa, 0xcc, 0xb0, 0x1a,
	0x0a, 0x45, 0xbb, 0x50, 0x1b, 0x52, 0xd7, 0xb4, 0x43, 0xd9, 0x6d, 0x7d, 0xc7, 0xb3, 0xae, 0x02,
	0x79, 0x43, 0x77, 0x86, 0xd4, 0xed, 0x4a, 0xa4, 0x23, 0x00, 0x3e, 0x91, 0xc6, 0xc4, 0x0f, 0xa8,
	0xe7, 0xca, 0x07, 0x49, 0x7d, 0x72, 0xe6, 0xfd, 0xe0, 0xea, 0xdd, 0x98, 0xf1, 0xe4, 0x46, 0x66,
	0x3c, 0xf9, 0xcf, 0xcc, 0x0d, 0x58, 0x37, 0x88, 0xe5, 0x8d, 0x89, 0x9f, 0x9e, 0xd5, 0x27, 0x70,
	0x6f, 0x0e, 0x91, 0xa5, 0xfc, 0x29, 0xac, 0xbb, 0xe1, 0xd0, 0xf4, 0x23, 0x98, 0xd8, 0x66, 0x62,
	0x78, 0x73, 0xeb, 0x75, 0x37, 0x1c, 0x1a, 0x0a, 0x54, 0xa7, 0x79, 0xaf, 0xec, 0x47, 0xbb, 0x0c,
	0x4f, 0xff, 0x94, 0x05, 0x25, 0x85, 0x92, 0xe0, 0x33, 0xa8, 0x90, 0x09, 0xb1, 0x42, 0x11, 0xdc,
	0x80, 0x90, 0x74, 0x4b, 0xf7, 0x14, 0xc8, 0x0f, 0x95, 0x49, 0xe2, 0x6b, 0xe7, 0xe7, 0x0c, 0x94,
	0x93, 0xef, 0x17, 0xd2, 0xa0, 0x7c, 0xda, 0x3b, 0xee, 0x1e, 0x1d, 0x7f, 0x65, 0x9e, 0x9c, 0xf6,
	0x8e, 0xb5, 0x25, 0x84, 0xa0, 0xaa, 0x24, 0x2f, 0x4f, 0xbb, 0xfb, 0x2f, 0x7a, 0x5a, 0x06, 0xad,
	0x42, 0x56, 0xa0, 0xcb, 0xa8, 0x04, 0x85, 0xde, 0xeb, 0xd3, 0x23, 0xa3, 0xd7, 0xd5, 0x56, 0x92,
	0xaa, 0x07, 0xcf, 0x4f, 0xce, 0x7a, 0x5d, 0x2d, 0x8b, 0x00, 0xf2, 0xf2, 0x77, 0x0e, 0xd5, 0x60,
	0xcd, 0xe8, 0x1d, 0x9c, 0x9c, 0xf7, 0x8c, 0x6f, 0xcc, 0x67, 0xfb, 0x47, 0xcf, 0x7b, 0x5d, 0x2d,
	0xbf, 0xf7, 0x5b, 0x11, 0xf2, 0x2f, 0x44, 0xfb, 0xa0, 0x57, 0x50, 0x4a, 0xac, 0x6a, 0xa8, 0x19,
	0xbf, 0x49, 0xe9, 0x91, 0xd7, 0x4c, 0x4f, 0x19, 0x7d, 0xe3, 0x97, 0xbf, 0xdf, 0xfe, 0xb9, 0x7c,
	0x57, 0xd7, 0xda, 0xe3, 0x8f, 0xdb, 0x96, 0x33, 0x6c, 0xab, 0x5b, 0xfe, 0x3c, 0xb3, 0x83, 0x2c,
	0x28, 0x27, 0x37, 0x29, 0xb4, 0xa1, 0x4e, 0x2f, 0x58, 0xbb, 0x9a, 0x0f, 0x16, 0x83, 0xf2, 0x21,
	0x68, 0x08, 0x1e, 0x84, 0xe6, 0x78, 0x38, 0x49, 0x72, 0x91, 0x89, 0x49, 0x16, 0xac, 0x4f, 0x31,
	0xc9, 0xa2, 0xdd, 0x47, 0x91, 0xec, 0xcc, 0x93, 0x4c, 0x60, 0x2d, 0xb5, 0x6e, 0xa0, 0x2d, 0x65,
	0x6a, 0xf1, 0x3a, 0xd4, 0x7c, 0x78, 0x23, 0x2e, 0xd9, 0xde, 0x17, 0x6c, 0x5b, 0xfa, 0xfd, 0x34,
	0x5b, 0x5b, 0xad, 0x1f, 0xfc, 0x0e, 0x19, 0x54, 0x67, 0x57, 0x00, 0xb4, 0xa9, 0x0c, 0x2f, 0xdc,
	0x4a, 0x9a, 0x5b, 0x37, 0xc1, 0x92, 0xf6, 0x91, 0xa0, 0xdd, 0xd4, 0x1b, 0x73, 0xb4, 0x72, 0x23,
	0xe0, 0xac, 0x6f, 0x60, 0x2d, 0xd5, 0x57, 0x71, 0xbc, 0x8b, 0x5b, 0x31, 0x8e, 0xf7, 0x86, 0x86,
	0xfc, 0x17, 0x62, 0xd9, 0xa3, 0x9c, 0x18, 0x43, 0x29, 0x31, 0x3e, 0xe3, 0x5a, 0x9c, 0x9f, 0xdb,
	0xcd, 0x8d, 0x85, 0x98, 0x24, 0xbb, 0x2f, 0xc8, 0x6a, 0x7a, 0x55, 0x91, 0x89, 0xf7, 0x5a, 0x54,
	0xe5, 0x77, 0x00, 0xf1, 0xe4, 0x43, 0xf7, 0x93, 0x65, 0x37, 0x33, 0x22, 0x9b, 0xcd, 0x45, 0x90,
	0xb4, 0xbf, 0x2e, 0xec, 0x6b, 0x28, 0x65, 0x1f, 0x39, 0x50, 0x4a, 0xcc, 0xb1, 0xd8, 0xff, 0xf9,
	0x99, 0x18, 0xfb, 0xbf, 0x68, 0xf0, 0xc9, 0xe2, 0xd8, 0x79, 0x30, 0x6b, 0xbf, 0xfd, 0x63, 0x62,
	0x14, 0xfd, 0x84, 0x5e, 0x03, 0xc4, 0x0f, 0x53, 0x1c, 0xca, 0xdc, 0x0b, 0x16, 0x87, 0x32, 0xff,
	0x8e, 0xe9, 0x35, 0x41, 0x55, 0x41, 0x25, 0x45, 0x35, 0x20, 0x04, 0x39, 0x50, 0xe9, 0x60, 0x66,
	0x5d, 0x9e, 0xb9, 0x78, 0x14, 0x5c, 0x7a, 0x0c, 0x4d, 0x3b, 0x67, 0x46, 0xac, 0xec, 0x6f, 0xde,
	0x80, 0x4a, 0x8a, 0x2d, 0x41, 0xd1, 0x40, 0xeb, 0x8a, 0xa2, 0xcf, 0xd5, 0xda, 0x81, 0xd4, 0xeb,
	0x7c, 0xf0, 0xed, 0xa3, 0x0b, 0xca, 0x2e, 0xc3, 0xfe, 0xae, 0xe5, 0x0d, 0xdb, 0x0e, 0xdf, 0xfb,
	0x5c, 0xea, 0x5e, 0x38, 0xb8, 0x1f, 0xb4, 0x1d, 0x67, 0xd8, 0x8e, 0x8c, 0xf7, 0xf3, 0xe2, 0xbf,
	0xe5, 0x27, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xbf, 0x62, 0xdc, 0xa3, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TraderClient is the client API for Trader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TraderClient interface {
	InitAccount(ctx context.Context, in *InitAccountRequest, opts ...grpc.CallOption) (*Account, error)
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	CloseAccount(ctx context.Context, in *CloseAccountRequest, opts ...grpc.CallOption) (*CloseAccountResponse, error)
	WithdrawAccount(ctx context.Context, in *WithdrawAccountRequest, opts ...grpc.CallOption) (*WithdrawAccountResponse, error)
	DepositAccount(ctx context.Context, in *DepositAccountRequest, opts ...grpc.CallOption) (*DepositAccountResponse, error)
	RecoverAccounts(ctx context.Context, in *RecoverAccountsRequest, opts ...grpc.CallOption) (*RecoverAccountsResponse, error)
	SubmitOrder(ctx context.Context, in *SubmitOrderRequest, opts ...grpc.CallOption) (*SubmitOrderResponse, error)
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	AuctionFee(ctx context.Context, in *AuctionFeeRequest, opts ...grpc.CallOption) (*AuctionFeeResponse, error)
	BatchSnapshot(ctx context.Context, in *BatchSnapshotRequest, opts ...grpc.CallOption) (*BatchSnapshotResponse, error)
}

type traderClient struct {
	cc *grpc.ClientConn
}

func NewTraderClient(cc *grpc.ClientConn) TraderClient {
	return &traderClient{cc}
}

func (c *traderClient) InitAccount(ctx context.Context, in *InitAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/clmrpc.Trader/InitAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traderClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.Trader/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traderClient) CloseAccount(ctx context.Context, in *CloseAccountRequest, opts ...grpc.CallOption) (*CloseAccountResponse, error) {
	out := new(CloseAccountResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.Trader/CloseAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traderClient) WithdrawAccount(ctx context.Context, in *WithdrawAccountRequest, opts ...grpc.CallOption) (*WithdrawAccountResponse, error) {
	out := new(WithdrawAccountResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.Trader/WithdrawAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traderClient) DepositAccount(ctx context.Context, in *DepositAccountRequest, opts ...grpc.CallOption) (*DepositAccountResponse, error) {
	out := new(DepositAccountResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.Trader/DepositAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traderClient) RecoverAccounts(ctx context.Context, in *RecoverAccountsRequest, opts ...grpc.CallOption) (*RecoverAccountsResponse, error) {
	out := new(RecoverAccountsResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.Trader/RecoverAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traderClient) SubmitOrder(ctx context.Context, in *SubmitOrderRequest, opts ...grpc.CallOption) (*SubmitOrderResponse, error) {
	out := new(SubmitOrderResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.Trader/SubmitOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traderClient) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	out := new(ListOrdersResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.Trader/ListOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traderClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.Trader/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traderClient) AuctionFee(ctx context.Context, in *AuctionFeeRequest, opts ...grpc.CallOption) (*AuctionFeeResponse, error) {
	out := new(AuctionFeeResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.Trader/AuctionFee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *traderClient) BatchSnapshot(ctx context.Context, in *BatchSnapshotRequest, opts ...grpc.CallOption) (*BatchSnapshotResponse, error) {
	out := new(BatchSnapshotResponse)
	err := c.cc.Invoke(ctx, "/clmrpc.Trader/BatchSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TraderServer is the server API for Trader service.
type TraderServer interface {
	InitAccount(context.Context, *InitAccountRequest) (*Account, error)
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	CloseAccount(context.Context, *CloseAccountRequest) (*CloseAccountResponse, error)
	WithdrawAccount(context.Context, *WithdrawAccountRequest) (*WithdrawAccountResponse, error)
	DepositAccount(context.Context, *DepositAccountRequest) (*DepositAccountResponse, error)
	RecoverAccounts(context.Context, *RecoverAccountsRequest) (*RecoverAccountsResponse, error)
	SubmitOrder(context.Context, *SubmitOrderRequest) (*SubmitOrderResponse, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	AuctionFee(context.Context, *AuctionFeeRequest) (*AuctionFeeResponse, error)
	BatchSnapshot(context.Context, *BatchSnapshotRequest) (*BatchSnapshotResponse, error)
}

// UnimplementedTraderServer can be embedded to have forward compatible implementations.
type UnimplementedTraderServer struct {
}

func (*UnimplementedTraderServer) InitAccount(ctx context.Context, req *InitAccountRequest) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitAccount not implemented")
}
func (*UnimplementedTraderServer) ListAccounts(ctx context.Context, req *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccounts not implemented")
}
func (*UnimplementedTraderServer) CloseAccount(ctx context.Context, req *CloseAccountRequest) (*CloseAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseAccount not implemented")
}
func (*UnimplementedTraderServer) WithdrawAccount(ctx context.Context, req *WithdrawAccountRequest) (*WithdrawAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawAccount not implemented")
}
func (*UnimplementedTraderServer) DepositAccount(ctx context.Context, req *DepositAccountRequest) (*DepositAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DepositAccount not implemented")
}
func (*UnimplementedTraderServer) RecoverAccounts(ctx context.Context, req *RecoverAccountsRequest) (*RecoverAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverAccounts not implemented")
}
func (*UnimplementedTraderServer) SubmitOrder(ctx context.Context, req *SubmitOrderRequest) (*SubmitOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOrder not implemented")
}
func (*UnimplementedTraderServer) ListOrders(ctx context.Context, req *ListOrdersRequest) (*ListOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}
func (*UnimplementedTraderServer) CancelOrder(ctx context.Context, req *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (*UnimplementedTraderServer) AuctionFee(ctx context.Context, req *AuctionFeeRequest) (*AuctionFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuctionFee not implemented")
}
func (*UnimplementedTraderServer) BatchSnapshot(ctx context.Context, req *BatchSnapshotRequest) (*BatchSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchSnapshot not implemented")
}

func RegisterTraderServer(s *grpc.Server, srv TraderServer) {
	s.RegisterService(&_Trader_serviceDesc, srv)
}

func _Trader_InitAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraderServer).InitAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.Trader/InitAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraderServer).InitAccount(ctx, req.(*InitAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trader_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraderServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.Trader/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraderServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trader_CloseAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraderServer).CloseAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.Trader/CloseAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraderServer).CloseAccount(ctx, req.(*CloseAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trader_WithdrawAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraderServer).WithdrawAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.Trader/WithdrawAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraderServer).WithdrawAccount(ctx, req.(*WithdrawAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trader_DepositAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraderServer).DepositAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.Trader/DepositAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraderServer).DepositAccount(ctx, req.(*DepositAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trader_RecoverAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraderServer).RecoverAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.Trader/RecoverAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraderServer).RecoverAccounts(ctx, req.(*RecoverAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trader_SubmitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraderServer).SubmitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.Trader/SubmitOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraderServer).SubmitOrder(ctx, req.(*SubmitOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trader_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraderServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.Trader/ListOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraderServer).ListOrders(ctx, req.(*ListOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trader_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraderServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.Trader/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraderServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trader_AuctionFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuctionFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraderServer).AuctionFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.Trader/AuctionFee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraderServer).AuctionFee(ctx, req.(*AuctionFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Trader_BatchSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TraderServer).BatchSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clmrpc.Trader/BatchSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TraderServer).BatchSnapshot(ctx, req.(*BatchSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Trader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clmrpc.Trader",
	HandlerType: (*TraderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitAccount",
			Handler:    _Trader_InitAccount_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _Trader_ListAccounts_Handler,
		},
		{
			MethodName: "CloseAccount",
			Handler:    _Trader_CloseAccount_Handler,
		},
		{
			MethodName: "WithdrawAccount",
			Handler:    _Trader_WithdrawAccount_Handler,
		},
		{
			MethodName: "DepositAccount",
			Handler:    _Trader_DepositAccount_Handler,
		},
		{
			MethodName: "RecoverAccounts",
			Handler:    _Trader_RecoverAccounts_Handler,
		},
		{
			MethodName: "SubmitOrder",
			Handler:    _Trader_SubmitOrder_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _Trader_ListOrders_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _Trader_CancelOrder_Handler,
		},
		{
			MethodName: "AuctionFee",
			Handler:    _Trader_AuctionFee_Handler,
		},
		{
			MethodName: "BatchSnapshot",
			Handler:    _Trader_BatchSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trader.proto",
}
